<?php

define('NIVEL_EDUCATIVO_SECUNDARIA',1);
define('NIVEL_EDUCATIVO_BACHILLERATO',2);
define('NIVEL_EDUCATIVO_UNIVERSIDAD',3);
define('SIN_REGISTROS',0);
define('SIN_ARCHIVO',0);
define('PERMISOS_UNMASK', 000);
define('PERMISOS_FOLDER', 0755);
define("INICIO_CADENA",0);
define("FIN_CADENA_NEG",-4);
define('ESTADO_ACTIVO',1);
define('ESTADO_INACTIVO',0);
